export type ServiceCategory={name:string;slug:string;tagline:string;services:string[]};
export const categories:ServiceCategory[]=[
{name:'Managed IT',slug:'managed-it',tagline:'Reliable support for people, devices and day-to-day technology.',services:['Remote help desk','Onsite support','Desktop support','PC & Mac setup','Device management','Patch management','Software deployment','Server administration','Employee onboarding/offboarding','Hardware procurement','Lifecycle management']},
{name:'Microsoft & Google',slug:'microsoft-google',tagline:'Productivity, identity and collaboration configured correctly.',services:['Microsoft 365','Google Workspace','Exchange Online','SharePoint','OneDrive','Teams','Microsoft Entra ID','Intune','Microsoft Copilot','Workspace AI','Tenant migrations','License optimization']},
{name:'Cloud',slug:'cloud',tagline:'Secure cloud foundations that can grow with your business.',services:['Microsoft Azure','AWS','Google Cloud','Cloud migrations','Cloud infrastructure','Virtual servers','Storage','Cloud optimization','Backup','Disaster recovery']},
{name:'Cybersecurity',slug:'cybersecurity',tagline:'Layered security for identities, devices, email and data.',services:['Endpoint protection','EDR/XDR','Email security','MFA','Identity security','SSO','Vulnerability management','Security assessments','Security awareness','Zero Trust','Conditional Access','Security monitoring','Incident response']},
{name:'Networking',slug:'networking',tagline:'Fast, secure connectivity for every office and remote worker.',services:['Business Wi-Fi','Firewalls','VPN','Routers','Switches','Network monitoring','Network design','Office cabling','New office setup','Network troubleshooting']},
{name:'Communications',slug:'communications',tagline:'Modern voice, meetings, messaging and customer communications.',services:['VoIP','Microsoft Teams Phone','Zoom Phone','Contact center','SMS','Business texting','Video conferencing','Call routing']},
{name:'AI for Business',slug:'ai',tagline:'Practical AI that does useful work inside your business.',services:['AI readiness assessment','Microsoft Copilot','ChatGPT Business','AI employee assistants','AI knowledge assistants','Website assistants','Customer service agents','AI receptionists','Voice AI','Sales assistants','Email assistants','Document processing','Data extraction','AI workflow automation','AI agent development','Multi-agent systems','AI monitoring','AI governance','AI security','AI training']},
{name:'Automation & Integration',slug:'automation',tagline:'Connect systems and remove repetitive manual work.',services:['Business process automation','CRM automation','Email automation','Document automation','API integrations','Webhooks','Database integrations','SaaS integrations','Power Automate','n8n','Zapier','Make','Custom workflows']},
{name:'Software Development',slug:'development',tagline:'Custom software when off-the-shelf tools are not enough.',services:['Internal applications','Customer portals','APIs','Dashboards','Reporting systems','Database applications','Integration middleware','AI applications','Custom automation']},
{name:'Professional Services',slug:'professional',tagline:'Experienced hands for assessments, migrations and projects.',services:['Technology consulting','IT assessments','AI assessments','Cloud assessments','Cybersecurity assessments','IT strategy','Technology roadmaps','Office moves','Migrations','IT projects','AI projects']}
];
export const allServices=categories.flatMap(c=>c.services.map(name=>({name,category:c.name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-')})));
