import Link from 'next/link';
import {ArrowRight,BrainCircuit,CheckCircle2,Cloud,Headphones,Network,ShieldCheck,Sparkles,Workflow,MonitorCog,PhoneCall,Database,LockKeyhole,Bot,Gauge,CircleCheckBig} from 'lucide-react';
import {PublicShell} from '@/components/public-shell';
const pillars=[
['Managed IT',Headphones,'End-user support, devices, servers, onboarding and day-to-day IT operations.',['Help desk & onsite support','Device & patch management','Microsoft 365 administration']],
['Cybersecurity',ShieldCheck,'Layered protection for identities, endpoints, email, networks and business data.',['MFA & identity security','Endpoint protection / EDR','Security assessments']],
['Cloud & Infrastructure',Cloud,'Modernize infrastructure without losing visibility, control or support.',['Microsoft 365 & Azure','AWS / Google Cloud','Backup & disaster recovery']],
['AI & Automation',BrainCircuit,'Put practical AI to work across customer service, operations and employee workflows.',['AI agents & assistants','Voice AI & receptionists','Workflow automation']],
['Networking & Voice',Network,'Reliable connectivity and communications for offices, remote teams and customers.',['Wi-Fi, firewalls & VPN','VoIP & Teams Phone','Network monitoring']],
['Custom Solutions',Workflow,'Connect systems, automate handoffs and build the software your operation actually needs.',['API & SaaS integrations','Internal apps & portals','Dashboards & reporting']]] as const;
export default function Home(){return <PublicShell><main>
<section className="hero2"><div className="shell heroGrid"><div><div className="eyebrow">IT + AI SERVICES FOR MODERN BUSINESS</div><h1>Your technology should move the business <em>forward.</em></h1><p className="lead">SolidITPro brings managed IT, cybersecurity, cloud, communications, automation and AI together under one accountable technology partner. Choose exactly what you need today and expand as you grow.</p><div className="actions"><Link className="btn btnLg" href="/build-your-solution">Build Your Solution <ArrowRight size={18}/></Link><Link className="btnGhost btnLg" href="/contact">Talk to an Expert</Link></div><div className="heroTrust"><span><CheckCircle2/>Flexible service catalog</span><span><CheckCircle2/>Human-led AI</span><span><CheckCircle2/>Colorado based</span></div></div><div className="heroVisual"><div className="opsWindow"><div className="windowTop"><span/><span/><span/><b>SolidITPro Operations</b></div><div className="opsBody"><div className="opsSide"><i/><i/><i/><i/><i/></div><div className="opsMain"><div className="miniLabel">YOUR TECHNOLOGY ENVIRONMENT</div><div className="healthRow"><div><b>98%</b><span>Device health</span></div><div><b>24/7</b><span>Monitoring</span></div><div><b>12</b><span>Automations</span></div></div><div className="signal"><span>AI work queue</span><b>7 tasks routed</b></div><div className="signal"><span>Security posture</span><b className="ok">Protected</b></div><div className="signal"><span>Open support requests</span><b>3 active</b></div></div></div></div><div className="floatCard fc1"><Bot/><div><b>AI + Human Operations</b><span>Policy-controlled execution</span></div></div><div className="floatCard fc2"><ShieldCheck/><div><b>Security built in</b><span>Identity • Endpoint • Data</span></div></div></div></div></section>
<section className="logoBand"><div className="shell"><span>Built around the platforms businesses already use</span><div className="wordLogos"><b>Microsoft 365</b><b>Azure</b><b>Google Workspace</b><b>AWS</b><b>Zoom</b><b>Intune</b></div></div></section>
<section className="section"><div className="shell"><div className="sectionIntro"><div><div className="eyebrow">ONE PARTNER. A COMPLETE TECHNOLOGY STACK.</div><h2>Pick the capabilities you need.<br/>We make them work together.</h2></div><p className="sub">Most small businesses outgrow fragmented vendors. SolidITPro gives you a modular service catalog with one team responsible for how the pieces connect.</p></div><div className="pillarGrid">{pillars.map(([name,Icon,desc,items])=><Link href="/services" className="pillar" key={name}><div className="pillarIcon"><Icon/></div><h3>{name}</h3><p>{desc}</p><ul>{items.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul><span className="learn">Explore capabilities <ArrowRight/></span></Link>)}</div></div></section>
<section className="section sectionInk"><div className="shell"><div className="sectionIntro light"><div><div className="eyebrow">AI THAT FITS THE WAY YOU WORK</div><h2>Move from “trying AI” to<br/>running AI in the business.</h2></div><p className="sub">We design AI around real workflows—not demos. Start with one useful assistant or automation, then expand into coordinated agents with governance and human oversight.</p></div><div className="aiStage"><div className="aiFlow"><div className="flowNode"><PhoneCall/><b>Customer request</b><span>Phone • Email • Portal</span></div><ArrowRight className="flowArrow"/><div className="flowNode featured"><Sparkles/><b>AI Operations Manager</b><span>Classify • Route • Coordinate</span></div><ArrowRight className="flowArrow"/><div className="flowStack"><div><Headphones/><span>IT Support Agent</span></div><div><ShieldCheck/><span>Security Agent</span></div><div><MonitorCog/><span>Microsoft 365 Agent</span></div><div><Workflow/><span>Automation Agent</span></div></div><ArrowRight className="flowArrow"/><div className="flowNode"><CircleCheckBig/><b>Human-approved outcome</b><span>Delivered + documented</span></div></div><div className="aiFoot"><span><LockKeyhole/>Sensitive actions require approval</span><span><Database/>Tenant-isolated knowledge</span><span><Gauge/>Every run is auditable</span></div></div><div className="actions"><Link className="btn btnLg" href="/ai-solutions">Explore AI Solutions <ArrowRight size={18}/></Link></div></div></section>
<section className="section sectionSoft"><div className="shell split featureSplit"><div><div className="eyebrow">BUILD YOUR SOLUTION</div><h2>Don't squeeze your business into somebody else's package.</h2><p className="sub">Tell us your size, environment and priorities. Select any combination of IT, cloud, security, communications, AI and automation. We'll turn it into a preliminary technology plan.</p><div className="actions"><Link className="btn btnLg" href="/build-your-solution">Start your assessment <ArrowRight size={18}/></Link></div></div><div className="solutionPreview"><div className="spTop"><span>PRELIMINARY TECHNOLOGY PLAN</span><b>Professional Services • 25 users</b></div>{['Managed IT & device management','Microsoft 365 administration','Endpoint + email security','Cloud backup & recovery','AI knowledge assistant','Employee onboarding automation'].map((x,i)=><div className="spRow" key={x}><span className="spNum">0{i+1}</span><b>{x}</b><CheckCircle2/></div>)}</div></div></section>
<section className="section"><div className="shell"><div className="sectionIntro"><div><div className="eyebrow">HOW SOLIDITPRO WORKS</div><h2>One operating model from request to resolution.</h2></div><p className="sub">Whether work begins with a support ticket, an alert, a project or an AI opportunity, it enters the same accountable workflow.</p></div><div className="processGrid">{[['01','Discover','Understand the business, users, systems and risks.'],['02','Design','Select the right services, controls and integrations.'],['03','Implement','Deploy with clear ownership, testing and documentation.'],['04','Operate','Monitor, support, automate and continuously improve.']].map(([n,t,d])=><div className="process" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="ctaBand"><div className="shell ctaInner"><div><div className="eyebrow">READY TO MODERNIZE YOUR TECHNOLOGY?</div><h2>Start with the problem you want solved.</h2><p>We'll help you choose the right combination of IT and AI services.</p></div><div className="actions"><Link className="btn btnLg" href="/build-your-solution">Build Your Solution</Link><Link className="btnWhite btnLg" href="/contact">Talk to an Expert</Link></div></div></section>
</main></PublicShell>}
